spring:
  application:
    name: time-tracking-api
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker
    username:
    password:
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration